@echo off
echo Activating venv...
call C:\Users\nikol\.venv\Scripts\Activate.bat
echo Installing requirements...
pip install -r requirements.txt
echo Running migrations...
python manage.py makemigrations users
python manage.py migrate
echo Creating superuser...
python manage.py createsuperuser
echo Collecting static...
python manage.py collectstatic --noinput
echo Done.
