# Generated by Django 5.2.15 on 2026-07-07 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover_image', models.ImageField(blank=True, upload_to='course-covers/', verbose_name='Обложка')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('hidden', 'Скрыт')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(default=1, verbose_name='Номер урока')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Краткое описание')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('video_url', models.URLField(blank=True, verbose_name='Видео URL')),
                ('video_file', models.FileField(blank=True, upload_to='lessons/videos/', verbose_name='Видео/аудио файл')),
                ('homework_text', models.TextField(blank=True, verbose_name='Домашнее задание')),
                ('status', models.CharField(choices=[('published', 'Опубликован'), ('draft', 'Черновик')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'ordering': ('order_number',),
                'unique_together': {('course', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='LessonFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lessons/files/', verbose_name='Файл')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='Тип')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.lesson', verbose_name='Урок')),
            ],
        ),
    ]
