# Generated by Django 5.2.15 on 2026-07-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
    ]
